
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:77 (project)"
    message: |
      The system is: Linux - 5.15.0-72-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/thijs/git/microhh-dev/microhh/build_gpu_sp/CMakeFiles/3.26.4/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/g++ 
      Build flags: ;-fopenmp
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/thijs/git/microhh-dev/microhh/build_gpu_sp/CMakeFiles/3.26.4/CompilerIdCXX/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" did not match "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is Clang using "" did not match "(clang version)":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" did not match "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is Clang using "" did not match "(clang version)":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" did not match "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is Clang using "" did not match "(clang version)":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" did not match "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is Clang using "" did not match "(clang version)":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.
      Compiler: /opt/nvidia/hpc_sdk/Linux_x86_64/22.7/compilers/bin/nvcc 
      Build flags: 
      Id flags:  -v
      
      The output was:
      1
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.
      Compiler: /opt/nvidia/hpc_sdk/Linux_x86_64/22.7/compilers/bin/nvcc 
      Build flags: 
      Id flags:  -v
      
      The output was:
      1
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" did not match "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is Clang using "" did not match "(clang version)":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" did not match "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is Clang using "" did not match "(clang version)":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" did not match "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1115 (message)"
      - "/snap/cmake/1299/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:77 (project)"
    message: |
      Checking whether the CUDA compiler is Clang using "" did not match "(clang version)":
      nvcc-Error-A CUDA toolkit matching the current driver version (12.1) or a supported older version (11.0 or 10.2) was not installed with this HPC SDK
...
